name: Coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: x64
    - run: pip install virtualenv==20.2.1
    - run: pip install nox==2019.11.9
    - run: pip install poetry==1.0.5
    - run: pip install nox-poetry==0.5.0
    - run: nox --sessions tests-3.8 coverage
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
