name: Tests
on: push
jobs:
  tests:
    name: Python ${{ matrix.python-version }}
    uses: Informasjonsforvaltning/workflows/.github/workflows/test-nox.yaml@main
    with:
      python_versions: '3.8','3.9'
      python_architecture: x64
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
